services:
  - type: web
    name: aegisalpha
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: APCA_API_KEY_ID
        sync: false
      - key: APCA_API_SECRET_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: PAPER
        value: "True"
